inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  Exclude:
    - 'extras/**/*'
    - 'locale/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Just so it looks like core Foreman
Layout/DotPosition:
  EnforcedStyle: "trailing"

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets
